name: helmholtz
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - numpy
  - scipy
  - matplotlib
  - h5py
  - pyyaml
  - pip
  - pip:
      - neuraloperator
